name: ui_components
description: "UI components package for OnMint Healthcare Platform"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  material_design_icons_flutter: ^7.0.7296
  fluttertoast: ^8.2.4
  cached_network_image: ^3.3.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: